name: Build macOS App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pillow fonttools pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller -D -w -n "JANCodeTool_mac" --splash Splash.png --add-data "JAN_ICON.ico:." JANcode-V24.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-App
          path: dist/JANCodeTool_mac
